practicemode: invalid return param
I am not sure with what versionb this is supposed to compile (e.g. your other projects depends on smlib, whcih seems to be for version 1.6?, at least I couldnt get to compile it without manually patching a few errors).

On 1.7 though this change is required:

```
ERROR: Failed to compile pugsetup_practicemode, from ./smbuild
././scripting/pugsetup_practicemode.sp(550) : error 180: function return type differs from prototype. expected 'void', but got 'int'
```